name: Install catboost

on: pull_request

jobs:
  install:
    runs-on: ubuntu-latest
    matrix:
      branch-or-commit: [
          "master", # fail
          "4059dfa5294c7b7d0220d5312c53e75bba9dd18e", # fail
          "9b0375cce7f142ef21c586d29721e920d4b3ebb6", # succeed
        ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.6"
      - run: |
          pip install wheel
          git clone https://github.com/catboost/catboost.git
          cd catboost/python-package
          git checkout ${{ matrix.branch-or-commit }}
          python setup.py bdist_wheel
