name: Install catboost

on: pull_request

jobs:
  fail:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.6"
      - run: |
          RUN pip install git+https://github.com/catboost/catboost.git@4059dfa5294c7b7d0220d5312c53e75bba9dd18e#subdirectory=catboost/python-package

  succeed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.6"
      - run: |
          RUN pip install git+https://github.com/catboost/catboost.git@9b0375cce7f142ef21c586d29721e920d4b3ebb6#subdirectory=catboost/python-package
